function MisureSpeimentaliLab1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  MISURESPEIMENTALILAB1 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  MISURESPEIMENTALILAB1 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  MISURESPEIMENTALILAB1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MisureSpeimentaliLab1 = importfile("/home/omarkahol/MATLAB/SPERIMENTALE/LAB1/Misure Speimentali Lab 1.xlsx", "Foglio1", [1, 35]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Oct-2021 18:22:20

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 35];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":G" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["GRADI", "MISURADELTAE1Delta_p1", "MISURADELTAE2Delta_p2", "PRIMIVALORI", "VarName5", "E1", "E2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Import the data
MisureSpeimentaliLab1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    MisureSpeimentaliLab1 = [MisureSpeimentaliLab1; tb]; %#ok<AGROW>
end

end